add_library(
    WebPttApi
    STATIC
        AppRouter.cpp
        Listener.cpp
        Router.cpp
        Session.cpp
        Utils.cpp
        WebSocketSession.cpp
)

target_include_directories(
    WebPttApi
    PUBLIC
        ${PROJECT_SOURCE_DIR}/src
)

target_link_libraries(
    WebPttApi
    PUBLIC
        project_options
        Boost::asio
        Boost::beast
        Boost::uuid
        datachannel
        glaze::glaze
        Threads::Threads
        spdlog::spdlog
)
